---
- hosts: all
  become: true
  
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
  
  - name: Install mysql client
    yum:
      name: mysql
      state: latest
      update_cache: yes
  
  - name: Check mysql version 
    command: sudo mysql -V
    register: mysql_version
  - debug:
      var: mysql_version.stdout

  - name: Enable mysql client service at startup
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Check mysql service status
    service_facts:
    register: services_state
  - debug:
    #  var: services_state.ansible_facts
      var: services_state.ansible_facts.services['mysql.service']
