---
- hosts: all
  become: true
  
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
  
  - name: Install mysql client
    yum:
      name: mysql
      state: latest
      update_cache: yes
  
  - name: Check mysql version 
    command: sudo mysql -V
    register: mysql_version
  - debug:
      var: mysql_version.stdout
