---
# tasks file for mysqlclient
- name: Update apt cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_distribution == "Ubuntu"

- name: Update all packages (Amazon)
  ansible.builtin.dnf:
    name: '*'
    update_only: true
  when: ansible_distribution == "Amazon"

- name: Install mysql client (Amazon)
  ansible.builtin.dnf:
    name: mysql
    update_cache: true
  when: ansible_distribution == "Amazon"

- name: Check mysqlclient version
  ansible.builtin.debug:
    var: mysqlclient_mysql_version.stdout
  when: ansible_distribution == "Amazon"
  notify:
    - Get mysql version (Amazon)

- name: Run handlers
  ansible.builtin.meta: flush_handlers

- name: Install mysql-client (Ubuntu)
  ansible.builtin.apt:
    name: mysql-client
    update_cache: true
  when: ansible_distribution == "Ubuntu"
