---
# tasks file for mysqlclient
- name: Update apt cache if needed
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: linux_distribution == "ubuntu"

- name: Update all packages (centos)
  yum:
    name: '*'
    state: latest
    update_only: yes
  when: linux_distribution == "centos"

- name: Install mysql client (centos)
  yum:
    name: mysql
    state: latest
    update_cache: yes
  when: linux_distribution == "centos"

- name: Check mysql version (centos)
  command: sudo mysql -V
  when: linux_distribution == "centos"
  register: mysql_version

- debug:
    var: mysql_version.stdout
  when: linux_distribution == "centos"

- name: Install mysql-client (ubuntu)
  apt:
    name: mysql-client
    state: latest
    update_cache: true
  when: linux_distribution == "ubuntu"
