---
# tasks file for mysqlclient
- name: Update apt cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_distribution == "Ubuntu"

- name: Update all packages (Amazon)
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
  when: ansible_distribution == "Amazon"

- name: Install mysql client (Amazon)
  ansible.builtin.yum:
    name: mysql
    state: latest
    update_cache: true
  when: ansible_distribution == "Amazon"

- name: Check mysql version (Amazon)
  ansible.builtin.command: sudo mysql -V
  when: ansible_distribution == "Amazon"
  register: mysql_version

- ansible.builtin.debug:
    var: mysql_version.stdout
  when: ansible_distribution == "Amazon"

- name: Install mysql-client (Ubuntu)
  ansible.builtin.apt:
    name: mysql-client
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"
