name: Deploy Infra
on:
  workflow_dispatch:

# Define environment variables used throughout the workflow
env:
  TF_WORKING_DIR: ./terraform  
  PKR_WORKING_DIR: ./packer/centos    
  ANSIBLE_WORKING_DIR: ./ansible 
  AWS_REGION: us-east-1

  TF_HTTP_ADDRESS: "https://gitlab.com/api/v4/projects/${{ vars.GL_PROJECT_ID }}/terraform/state/${{ vars.TF_STATE_NAME }}"
  TF_HTTP_LOCK_ADDRESS: "https://gitlab.com/api/v4/projects/${{ vars.GL_PROJECT_ID }}/terraform/state/${{ vars.TF_STATE_NAME }}/lock"
  TF_HTTP_UNLOCK_ADDRESS: "https://gitlab.com/api/v4/projects/${{ vars.GL_PROJECT_ID }}/terraform/state/${{ vars.TF_STATE_NAME }}/lock"
  TF_HTTP_USERNAME: ${{ vars.GL_USERNAME }}
  TF_HTTP_PASSWORD: ${{ secrets.GITLAB_TF_TOKEN }}
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: "5"         

jobs:
  
  ###################################################################################
  # JOB 1: TERRAFORM APPLY (Runs MANUALLY)
  ###################################################################################
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.x

    - name: Terraform Init
      id: init_tf
      run: terraform init
    
    - name: Terraform Apply
      id: apply_tf
      run: terraform apply -auto-approve
